#!/opt/pwn.college/bash

if [ -f /tmp/answer ]; then
    target_hash=$(cat /expected_commit)
    user_hash=$(cat /tmp/answer | tr -d ' \n')
    if [ "$user_hash" = "$target_hash" ]; then
        echo "[+] 正确！这是你的 flag："
        cat /flag
    else
        echo "[-] 提交的 commit hash 不正确，请再试一次！"
        exit 1
    fi
else
    echo "[-] 未找到 /tmp/answer 文件！"
    exit 1
fi
